### ISSUE TITLE
Version 0.8.3.2 is not available on Windows Python 2 nor Linux Python 3

### ISSUE THREAD

**Issue by sdc50** [conda-forge/ulmo-feedstock#6]

**Comment by dharhas** [comment]
@ocefpaf is there a reason why the binaries did not post for these two variants. Is there a way I can re-render the feedstock?

**Comment by ocefpaf** [comment]
The auto re-render has a `[ci skip]`, that only CircleCI obeys BTW, which won't produce the new packages even though the extra matrix item was added (PY36). So a manual re-render (actually only a CI trigger) should do it.

I will investigate the PY=2 though. That should exist already.

**Comment by dharhas** [comment]
looking here: https://anaconda.org/conda-forge/ulmo/files
we are missing win64/py27, linux64/py34 and linux64/py35 for v0.8.3.2

**Comment by dharhas** [comment]
@ocefpaf I just made a 0.8.4 release of ulmo. Once tests have finished running I'll merge the updated recipe in. So fixing the 0.8.3.2 binary availabiliy issue is not really needed anymore.

**Comment by ocefpaf** [comment]
I never got the time to see that happened with Python 2 package, sorry.
