### ISSUE TITLE
please help with this CondaHTTPError HTTP 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by aigalliano** [conda-forge/ulmo-feedstock#8]
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: 00:00.223877
CF-RAY: 3655ad560bed471c-EWR

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by dharhas** [comment]
This is a conda issue not a ulmo issue. I think this is a relevant link you can look at for some solutions: https://github.com/conda/conda/issues/3399

**Comment by aigalliano** [comment]
thank you so much.
